export interface PessoaFormData {
  id?: string | null;
  nome: string | null;
  email: string | null;
  telefone: string | null;
  dataNascimento: string | null;
  endereco: string | null;
  complemento: string | null;
  bairro: string | null;
  cidade: string | null;
  estado: string | null;
  cep: string | null;
  numeroCtps: string | null;
  serieCtps: string | null;
  dataEmissaoCtps: string | null;
  numeroRg: string | null;
  dataEmissaoRg: string | null;
  ufRg: string | null;
  cpf: string | null;
  pis: string | null;
  dataEmissaoPis: string | null;
  tituloEleitor: string | null;
  localNascimento: string | null;
  mae: string | null;
  pai: string | null;
  estadoCivil: string | null;
  categoriaCnh: string | null;
  numeroCnh: string | null;
  registroCnh: string | null;
  validadeCnh: string | null;
  chavePix: string | null;
  ativo?: boolean | null;
  // Campos de tamanho EPI
  tamanhoCamisa: string | null;
  tamanhoCalca: string | null;
  tamanhoCalcado: string | null;
  tamanhoLuva: string | null;
  tamanhoCapacete: string | null;
}
